- name: Getting files
  hosts: looneytunes # run against the entire planetexpress group
  connection: ssh      # use the connection module, ssh.py (this is the default)
  gather_facts: no       # do not run the module, setup.py, to define ansible_facts

  tasks:
  - name: create a directory
    file:
      path: challenge
      state: directory
  - name: "Download the file from url"
    get_url:
      url: https://raw.githubusercontent.com/csfeeser/ansible_essentials/main/data/downloadme.txt
      dest: challenge

  - name : Replace placeholder with name
    replace:
        path: ~/challenge/downloadme.txt
        regexp: "PLACEHOLDER"
        replace: "Vani"
        backup: yes
    become: true
